spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: fitnessrecommendation

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
